<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="arm_length" value="1.0" />
  <xacro:property name="arm_width" value="0.1" />
  <xacro:property name="arm_thickness" value="0.05" />
  <xacro:property name="arm_mass" value="1.0" />

  <!-- Arm Macro -->
  <xacro:macro name="arm" params="arm_name parent *origin *axis">
    <link name="${arm_name}">
      <visual>
        <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${arm_width} ${arm_thickness} ${arm_length}"/> 
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${arm_width} ${arm_thickness} ${arm_length}"/>  
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        <mass value="${arm_mass}"/>
        <inertia
          ixx="${arm_width}" ixy="0.0" ixz="0.0"
          iyy="${arm_thickness}" iyz="0.0"
          izz="${arm_length}"/>
      </inertial>
    </link>
    <joint name="${arm_name}_joint" type="continuous">
      <parent link="${parent}" />
      <child link="${arm_name}" />
      <xacro:insert_block name="origin" />
      <xacro:insert_block name="axis" />
    </joint>
  </xacro:macro>

</robot>